# Generated by Django 5.2.4 on 2026-01-29 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('content', models.TextField()),
                ('description', models.TextField()),
                ('url', models.URLField(db_index=True, max_length=2000, unique=True, validators=[django.core.validators.URLValidator()])),
                ('category', models.CharField(db_index=True, default='general', max_length=100)),
                ('source', models.CharField(db_index=True, max_length=200)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('url_to_image', models.URLField(blank=True, max_length=2000, null=True)),
                ('published_date', models.DateTimeField(db_index=True)),
                ('fetched_date', models.DateTimeField(auto_now_add=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('language', models.CharField(db_index=True, default='en', max_length=10)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['title', 'published_date'], name='news_articl_title_d4ee27_idx'), models.Index(fields=['source', 'published_date'], name='news_articl_source_41de77_idx'), models.Index(fields=['category', 'published_date'], name='news_articl_categor_e728a0_idx'), models.Index(fields=['language', 'published_date'], name='news_articl_languag_82b6bf_idx'), models.Index(fields=['is_featured', 'published_date'], name='news_articl_is_feat_9234c4_idx'), models.Index(fields=['is_archived', 'published_date'], name='news_articl_is_arch_84ce41_idx')],
                'unique_together': {('url', 'source')},
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('url', models.URLField(db_index=True, max_length=2000, validators=[django.core.validators.URLValidator()])),
                ('category', models.CharField(db_index=True, default='general', max_length=100)),
                ('language', models.CharField(db_index=True, default='en', max_length=10)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['country'], name='news_source_country_e21785_idx'), models.Index(fields=['category', 'language', 'country'], name='news_source_categor_b02426_idx'), models.Index(fields=['language', 'country'], name='news_source_languag_3b11b4_idx')],
            },
        ),
    ]
